# Some notes:
#   * OBS Canvas has a vertical resolution of 1080, so it doesn't make sense to have these go further than 1080.

cameras:
  vars:
      ansible_python_interpreter: "/usr/bin/python3"
  hosts:
    overhead-camera:
      ansible_host: camera-pi-a.local
      input_raspicam_args: |
        --awb off \
        -awbgainB 1.40 \
        -awbgainR 3.9 \
        -co 5 \
        -fps 30 \
        -quality 50 \
        -rot 90 \
        -sh 5 \
        -sa 5 \
        -ISO 100 \
        -x 1440 \
        -y 1080
      raspistill_args: |
        --nopreview \
        --rot 90
    fisheye-camera:
      ansible_host: camera-pi-b.local
      # Stuttering is a WiFi artifact, nothing really we can do.
      input_raspicam_args: |
        -fps 15 \
        -quality 30 \
        -rot 180 \
        -x 800 \
        -y 600
      raspistill_args: |
        --nopreview
    microscope-camera:
      ansible_host: camera-pi-c.local
      input_raspicam_args: |
        --awb off \
        -awbgainB 1.40 \
        -awbgainR 3.9 \
        -br 55 \
        -fps 30 \
        -preview \
        -quality 100 \
        -rot 90 \
        -x 860 \
        -y 1080
      raspistill_args: |
        --awb off \
        -awbg '3.9,1.40' \
        --brightness 55 \
        --nopreview \
        -rot 90 \
        -x 2421 \
        -y 3040
